import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components/site-footer";
import { Header } from "@/components/site-header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
	return (
		<html lang="en">
			<body>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
